# Build stage
FROM node:20-alpine AS builder
RUN apk update
RUN apk add git
RUN npm install -g @angular/cli
RUN npm install -g pm2
RUN npm install -g http-server
WORKDIR /app
RUN git clone https://github.com/Mate2145/Y.git
WORKDIR /app/Y/frontend/y_frontend
RUN npm install
EXPOSE 4200
CMD ["/bin/sh", "-c", "ng serve --host 0.0.0.0"]